name: CUPDailyReport

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *'
    # 现在UTC时间是19:30，北京时间是凌晨3:30

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout actions
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install requests

    - name: Run
      run: |
        # python TokenExpiredTest.py
        echo
        python LoadIndex.py
        echo
        python DailyReport.py
      env: 
        mytoken: ${{secrets.TOKEN}}
        serverkey: ${{secrets.SCKEY}}
        serverkey_turbo: ${{secrets.SENDKEY_TURBO}}
